### PR TITLE
Add combine function for Intervals.

### PR DESCRIPTION
**Pull request by cheecheeo**

### CODE REVIEW

**Comment by bokesan** [comment]
Hello John,

could you describe the usage scenario for `combine`? I need to decide whether to add this to the generic intervals, too, where it would be a much bigger change.

Also, I was actually considering to desupport the non-generic modules in the next major release. Do you specifically need these, or could you migrate to the generic versions?

Chris

**Comment by cheecheeo** [comment]
I have a mapreduce step in a data loading process that has interval values and I need to roll those intervals up if possible.

Looking around hackage the Interval type here seemed to be the most feature-ful interval type. If there was a generic combine I could use that just as well.

With combine implemented the reduce step becomes pretty simple.

**Comment by bokesan** [comment]
I see - you're using only the interval type. I was wondering where you'd use this operation in connection with maps, or if you needed it for a function like this: `flatten {[1,2], [3,4], (3,5), [7,8], (6,9)} == {[1,2], [3,5), (6,9)}`

I'll merge this, but won't add a corresponding method to the generic interval for now, since I'm not convinced that having constructors in the type class is the right thing.

It might be a few days before a new version shows up on hackage, since I have some other outstanding changes.

Thanks for contributing!

**Comment by bokesan** [comment]
One more question: I would have preferred to return `Maybe (Interval a)`. I.e. return `Nothing` if the intervals don't overlap. Would this be an acceptable change, or is the `Either` version much more convenient?

**Comment by cheecheeo** [comment]
The Maybe version would be fine. I can easily wrap it an Either for my case.

Thanks for the merge.

**Comment by cheecheeo** [comment]
In response to your flatten question: something like that is my end goal, I'm not sure how hard it would be to implement in the IntervalMap data structure. But, since my process is more mapreduce-y I can just use a foldl on lists and rely on the input lists being sorted by an external program.

**Pull request merged**
